version: '2'
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    restart: always
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
  grafana_init:
    entrypoint: "/opt/init.sh"
    depends_on:
      - grafana
    image: grafana/grafana:latest
    volumes:
      - ./init.sh:/opt/init.sh
    restart: always
  coinmarketcap-exporter:
    image: szukalski/coinmarketcap-exporter:latest
    restart: always
